### ISSUE TITLE
Ask about the embedding

### ISSUE THREAD

**Issue by zhangyuansen** [mengtong0110/InferDPT#1]
Hello, your work is really nice!

But I have a question, so how the embedding files are constructed? Are they constructed through the text-embedding-ada-002 APIs, or other approachs?

Looking forward to your reply!

Thanks

**Comment by mengtong0110** [comment]
Hi,

Thank you for your kind words! I'm glad you're interested in this work. We utilized the text-embedding-ada-002 model to construct the embedding files. Indeed, the text-embedding-ada-002 and GPT-4 models share the same embedding system, which can be found in more detail in the source code of tiktoken (https://github.com/openai/tiktoken). 

If you have any more questions or need further details, feel free to ask.

Best regards,

Meng Tong

**Comment by llCurious** [comment]
Hi, @mengtong0110 . Nice work!

I have three questions concerning the embedding process:
1. I notice that you truncate the input raw document to 50 tokens? Why do you do this? Is it just a demo or has to do the truncate?
2. What's the effect of the follow code in perturbing the raw document. It seems you just perform the encode/then decode. Wht's the difference?
```python
enc = tiktoken.encoding_for_model(model)
tokens_b=enc.encode(sent)
tokens=[(enc.decode_single_token_bytes(t)).decode('Latin-1') for t in tokens_b]
```
3. Have you tested the effect of using different tokenzier and embedding? Specifically, in the perturbing module and extraction module?

**Comment by mengtong0110** [comment]
Thank you @llCurious  for your thoughtful questions and for your appreciation of our work!

1. We truncate the input raw document to 50 tokens because, in open-ended text generation, evaluating the quality of the generated text often requires the model to generate a specific length of text based on a given prefix. Our token count design aligns with the experimental setups used in previous works [1],[2].

2. The code snippet:

```
    enc = tiktoken.encoding_for_model(model)
    tokens_b = enc.encode(sent)
    tokens = [(enc.decode_single_token_bytes(t)).decode('Latin-1') for t in tokens_b]
```

    is simply a method to convert a sentence into plaintext tokens. While there may be more efficient ways to achieve this, this approach serves its purpose effectively.

3. We have only tested our method with GPT-4, so we haven't explored other tokenizers. However, [3] has experimented with different tokenizers based on our proposed method.


[1] Welleck S, Kulikov I, Roller S, et al. Neural text generation with unlikelihood training[J]. arXiv preprint arXiv:1908.04319, 2019.
[2] Xu J, Liu X, Yan J, et al. Learning to break the loop: Analyzing and mitigating repetitions for neural text generation[J]. Advances in Neural Information Processing Systems, 2022, 35: 3082-3095.
[3] Fan T, Kang Y, Chen W, et al. PDSS: A Privacy-Preserving Framework for Step-by-Step Distillation of Large Language Models[J]. arXiv preprint arXiv:2406.12403, 2024.

**Comment by Cristliu** [comment]
Thanks for the nice code. But I'm wondering, if a dataset containing sensitive information is fed into the text-embedding-ada-002 API, which is also black-boxed, won't it leak sensitive information? Although that seems like the appropriate way to get Embedding for OpenAI models.

**Comment by mengtong0110** [comment]
> Thanks for the nice code. But I'm wondering, if a dataset containing sensitive information is fed into the text-embedding-ada-002 API, which is also black-boxed, won't it leak sensitive information? Although that seems like the appropriate way to get Embedding for OpenAI models.

Thank you for your valuable question. Regarding the construction of embeddings, we use the token vocabulary of GPT-4, so the issue you mentioned should not occur in our approach. However, if it involves personalized embedding construction outside of the InferDPT scheme, that could indeed pose a potential risk.
